spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  redis:
    host: 127.0.0.1
    port: '6379'
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:tcp://localhost/~/test;
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  config:
    activate:
      on-profile: local